const actions = {
    LOADER: 'LOADER',
    GROUP_ID: 'GROUP_ID',
    CHANEL_ID: 'CHANEL_ID',
    CONTACT_LIST: 'CONTACT_LIST',
    GROUP_CHANNEL: 'GROUP_CHANNEL',
    TOAST_MSG: 'TOAST_MSG',
    SHARE_MESSAGE: 'SHARE_MESSAGE',
    DARK_MODE: 'DARK_MODE',
    THEME_MODE: 'THEME_MODE',
    COLORS: 'COLORS',
    GROUP_TYPE: 'GROUP_TYPE',
    SELECTED_MEMBERS: 'SELECTED_MEMBERS',
    LOCAL_CONVERSATIONS: 'LOCAL_CONVERSATIONS',
    LOCAL_CHAT_MESSAGES: 'LOCAL_CHAT_MESSAGES',
};

export default actions;